services:
  frontend:
    environment:
      VITE_DEV_API_TARGET: http://backend:8000

  backend:
    ports:
      - 8001:8000
    environment:
      PROFILE_BASE_PATH: /app/browser_profiles
      PROFILE_BASE_PATH_HOST: /home/vpsroot/grokflow/browser_profiles
      VNC_NETWORK: grokflow_default
      VNC_IMAGE: grokflow/chrome-vnc:latest
    volumes:
      - ./browser_profiles:/app/browser_profiles
      - /var/run/docker.sock:/var/run/docker.sock

  worker:
    environment:
      PROFILE_BASE_PATH: /app/browser_profiles
      PROFILE_BASE_PATH_HOST: /home/vpsroot/grokflow/browser_profiles
      VNC_NETWORK: grokflow_default
      VNC_IMAGE: grokflow/chrome-vnc:latest
    volumes:
      - ./browser_profiles:/app/browser_profiles
      - /var/run/docker.sock:/var/run/docker.sock
